; ==================================================================================================
;Addresses of ION functions.
; ==================================================================================================

cmdshad		=966Eh
lVectors	=cmdshad+80
ionVersion	=lVectors
ionRandom	=lVectors+3
ionPutSprite	=lVectors+6
ionLargeSprite	=lVectors+9
ionGetPixel	=lVectors+12
ionFastCopy	=lVectors+15
ionDetect	=lVectors+18
ionDecompress	=lVectors+21

saferam1	=8265h
saferam2	=858Fh
saferam3	=80C9h
saferam4	=8039h





